#!/usr/bin/env ruby
def find_com(map, planet)
  return [] if map[planet] == "COM"
  find_com(map, map[planet]).unshift(map[planet])
end

orbits = $<.read.lines.map(&:chomp).map { |line| line.split(")") }
  .reduce(Hash.new) { |acc, (a, b)| acc[b] = a; acc }
you = find_com(orbits, "YOU")
san = find_com(orbits, "SAN")
common = (you & san).first
puts you.index(common) + san.index(common)
