#!/usr/bin/env ruby

class Amplifier
  def initialize(program, *input)
    @program = program.clone
    @next_amp = nil
    @input = input.clone
    @output = []
    @failed = false
    @idx = 0
  end

  def run
    while !halted?
      a, b, c = @program[@idx + 1, 3]
      a = @program[a] if @program[@idx].div(100).modulo(10).zero?
      b = @program[b] if @program[@idx].div(1000).modulo(10).zero?
      case intcode
      when 1 # add
        @program[c] = a + b
        @idx += 4
      when 2 # multiply
        @program[c] = a * b
        @idx += 4
      when 3 # read
        @program[@program[@idx + 1]] = @input.shift
        @idx += 2
      when 4 # write
        @output << @program[@program[@idx + 1]]
        @idx += 2
        @next_amp&.append_input(@output.last)
        @next_amp&.run
      when 5 # jump if true
        @idx = a != 0 ? b : @idx + 3
      when 6 # jump if false
        @idx = a.zero? ? b : @idx + 3
      when 7 # less than
        @program[c] = a < b ? 1 : 0
        @idx += 4
      when 8 # equals
        @program[c] = a == b ? 1 : 0
        @idx += 4
      else
        puts "program failed"
        @failed = true
        return nil
      end
    end
    return @output.last
  end

  def append_input(val)
    @input << val
  end

  def chain(amp)
    @next_amp = amp
  end

  def last_output
    @output.last
  end

  def halted?
    intcode == 99 || failed?
  end

  def failed?
    @failed
  end

  private

  def intcode
    @program[@idx] % 100
  end
end

# Create amplifiers and chain them so they create a feedback loop
# Should stop when one of them halts.
# If the input is correct then only Amp e should halt.
def calculate_thrust(input, phases)
  a, b, c, d, e = phases.map { |phase| Amplifier.new(input, phase) }
  a.chain(b).chain(c).chain(d).chain(e).chain(a)
  a.append_input(0)
  a.run
  e.last_output
end

def test1
  input = [3,26,1001,26,-4,26,3,27,1002,27,2,27,1,27,26,27,4,27,1001,28,-1,28,1005,28,6,99,0,0,5]
  phases = [9,8,7,6,5]
  puts calculate_thrust(input, phases)
end

def test2
  input = [3,52,1001,52,-5,52,3,53,1,52,56,54,1007,54,5,55,1005,55,26,1001,54,-5,54,1105,1,12,1,53,54,53,1008,54,0,55,1001,55,1,55,2,53,55,53,4,53,1001,56,-1,56,1005,56,6,99,0,0,0,0,10]
  phases = [9,7,8,5,6]
  puts calculate_thrust(input, phases)
end

def main
  input = $<.read.split(",").map(&:to_i)
  puts (5..9).to_a.permutation.map { |phases| calculate_thrust(input, phases) }.max
end

main
