#!/usr/bin/env ruby
# Part 1: 475
# Part 2: 297

def password? num
  list = num.digits.each_cons(2)
  list.all? { |x, y| x >= y} && list.any?{ |x, y| x == y }
end

part1 = (372304..847060).select { |n| password? n }
puts part1.count

part2 = part1.count { |n| n.digits.slice_when(&:!=).any? { |a| a.length == 2 } }
puts part2
